# 1.1 - Numpy  (Numerical Python)

**[Documentación](https://numpy.org/doc/stable/)**

**[Código fuente](https://github.com/numpy/numpy)**


![numpy](images/numpy.png)

NumPy es el paquete fundamental para computación cientifíca en python. Es una librería de python nos permite manejar vectores, matrices, [tensores](https://es.wikipedia.org/wiki/C%C3%A1lculo_tensorial) (arrays multidimensionales) y además realizar todas las operaciones matemáticas y lógicas de los mismos, como la manipulación de la dimensión, ordenado, selección, I/O, operaciones estadísticas, transformadas de Fourier, simulación aleatoria y un largo etcétera. Constituye la herramienta de álgebra lineal.

## Recordatorio de álgebra

+ Contenidos:

    + Concepto de tensor
    + Operaciones con vectores
        + Concepto de espacio vectorial y base
        + Suma de vectores
        + Producto escalar
        + Producto vectorial
    + Operaciones con matrices
        + Suma de matrices
        + Producto matricial
        + Matriz Identidad
        + Matriz Traspuesta (Hermítica)
        + Matriz Inversa 
        + Determinate

### Tensor

La palabra ['tensor'](https://es.wikipedia.org/wiki/C%C3%A1lculo_tensorial) se utiliza a menudo como abreviatura de campo tensorial, que es un valor tensorial definido en cada punto en una variedad. El primero en utilizar esta palabra fue William Rowan Hamilton en 1846, empleándola para lo que actualmente se conoce como módulo y fue Woldemar Voigt en 1899 quien la empleó en su acepción actual. La palabra tensor proviene del latín tensus, participio pasado de tendere 'estirar, extender'. El nombre se extendió porque la teoría de la elasticidad fue una de las primeras aplicaciones físicas donde se usaron tensores. Gregorio Ricci-Curbastro en 1890 desarrolló la notación actual con el nombre de geometría diferencial absoluta, y se popularizó con la publicación de Cálculo Diferencial Absoluto de Tullio Levi-Civita en 1900. Con la introducción de la teoría de la relatividad general por parte de Albert Einstein alrededor de 1915 se encontró su aplicación más pragmática. La Relatividad General es netamente tensorial. Einstein había aprendido del mismo Levi-Civita el uso de tensores con gran dificultad.

Podemos pensar en un tensor como la generalización del ente algebraico. Con un ejemplo se verá más claro.

Un **número**, cualquier número, $2$, $3.6$, $\pi$, $\phi$, $\sqrt{2}$, es un **tensor de rango $0$**.

Un **vector**, cualquier vector, sea como sea su longitud, $(1, 2, 3)$, $(0, 5, 2, 1, 5)$, $(9,2)$, es un **tensor de rango $1$**.

Una **matriz**, cualquier matriz, sean cuales sean sus dimensiones, es un **tensor de rango $2$**.

Un **cubo de Rubik** por ejemplo es un **tensor de rango $3$**.

Pensar en dimensiones superiores es complicado por no decir imposible, pero se pueden interpretar a través del contenido. Una **bolsa llena de cubos de Rubik** es un **tensor de rango $4$**.

Una **caja llena de bolsas que están llenas de cubos de Rubik es un tensor de rango $5$**.

Y así sucesivamente.

### Operaciones con vectores

**Espacio vectorial**

La definición matemática de [espacio vectorial](https://es.wikipedia.org/wiki/Espacio_vectorial) implica los conceptos de conjunto, ley de composición(operación) interna y ley de composición externa, definida sobre un segundo conjunto. Resumiendo, un espacio vectorial es una estructura creada sobre un conjunto no vacío con ambas leyes de composición. A los elementos de un espacio vectorial se les llama vectores.

Veamos un ejemplo:

Un espacio vectorial es el espacio tridimensional ${\Bbb R}^{3}$. Los elementos de ${\Bbb R}^{3}$ son vectores, por lo que la ley de composición interna es la suma de vectores. Para la ley de composición externa se necesita otro conjunto, que en esta caso son los números reales ${\Bbb R}$, y queda definida como el producto por escalares, multiplicar un vector por un número.



**Base vectorial**

Una [base](https://es.wikipedia.org/wiki/Base_(%C3%A1lgebra)) es un conjunto de vectores {$v_{1}, v_{2}, v_{3}, ... ,v_{n}$} que cumplen las siguientes propiedades:

+ Todos los elementos de la base pertenecen al mismo espacio vectorial.
+ Los elementos de la base forman un sistema linealmente independiente (ninguno es combinación lineal de los demás).
+ Cualquier elemento del espacio vectorial se puede escribir como combinación lineal de los elementos de la base (es lo que se llama sistema generador del espacio vectorial).

Ejemplo:

En ${\Bbb R}^{3}$, la base principal (llamada canónica) es {$(1,0,0), (0,1,0), (0,0,1)$}. Todos esos vectores pertenecen a ${\Bbb R}^{3}$, son linealmente independientes(ninguno puede ser una suma de los otros) y cualquier otro vector en ${\Bbb R}^{3}$ se puede representar como una suma de esos tres, una combinación lineal. No es única, otra base de ${\Bbb R}^{3}$ podría ser {$(1,1,1), (1,1,0), (1,0,0)$}



**Suma de vectores**

Los vectores se suman por componentes, lo que implica que ambos tienen la misma longitud. Por ejemplo en ${\Bbb R}^{3}$:

$$\vec{A}=A_{x}\vec{i}+A_{y}\vec{j}+A_{z}\vec{k}$$

$$\vec{B}=B_{x}\vec{i}+B_{y}\vec{j}+B_{z}\vec{k}$$

$$\vec{A}+\vec{B}=(B_{x}+A_{x})\vec{i}+(B_{y}+A_{y})\vec{j}+(B_{z}+A_{z})\vec{k}$$

$$$$

$$\vec{A}=(1,8,9)$$

$$\vec{B}=(4,3,0)$$

$$\vec{A}+\vec{B}=(5,11,9)$$



**Producto escalar**

Hay que diferenciar entre producto por escalares, un número por un vector resultando un vector, y el productor escalar donde se multiplican dos vectores resultando un número, un escalar.

+ Producto por escalares:

Se realiza elemento a elemento la multiplicación por el número:

$$\vec{A}=(1,8,9)$$

$$2*\vec{A}=(2,16,18)$$

+ Productos escalar:

Se realiza multiplicando elemento un vector fila por un vector columna y sumando los resultados. Hay que tener en cuenta, igual que en la suma, que ambos vectores tienen el mismo número de elementos. También se le llama producto punto (dot product) o producto interno (inner product).

$$\vec{A}\cdot\vec{B}=(1, 8, 9)\cdot\begin{pmatrix}4\\3\\0\end{pmatrix} = 1·4+8·3+9·0 = 4+24+0 = 28$$



**Producto vectorial**

En este caso, se multiplican dos vectores resultando otro vector. La manera más fácil de hacerlo es a través de un determinante:


$$\vec{A}\times \vec{B} = \begin{vmatrix}
\hat{\imath}&\hat{\jmath}&\hat{k}\\
1 & 8 & 9 \\
4 & 3 & 0
\end{vmatrix} = \begin{vmatrix}
8 & 9 \\
3 & 0
\end{vmatrix}·\hat{\imath} - 
\begin{vmatrix}
1 & 9 \\
4 & 0
\end{vmatrix}·\hat{\jmath} +
\begin{vmatrix}
1 & 8 \\
4 & 3
\end{vmatrix}·\hat{k} = (8·0-9·3)·\hat{\imath}-(1·0-9·4)·\hat{\jmath}+(1·3-8·4)·\hat{k}$$

$$\vec{A}\times \vec{B} = (-27, 36, -29)$$

### Operaciones con matrices


**Suma de matrices**

Las matrices tienen definidas sus dimensiones sugún el número de filas($m$) y de columnas($n$), y se representan como $A_{mxn}$. Para sumar matrices las dimensiones tienen que ser las mismas, igual que ocurría con los vectores, y se realiza elemento a elemento (element wise):


$$\begin{pmatrix}
5 & 7 & 1 \\
4 & 0 & 2 
\end{pmatrix}+\begin{pmatrix}
0 & 0 & 3 \\
2 & 2 & 7 
\end{pmatrix}=\begin{pmatrix}
5 & 7 & 4 \\
6 & 2 & 9 
\end{pmatrix}$$



**Producto matricial**

Para multiplicar matrices tenemos que tener en cuenta las dimensiones, porque el producto matricial no es conmutativo e incluso a veces no se puede realizar. El número de columnas de la primera matriz tiene que ser igual que el número de filas de la segunda y el resultado tendrá el número de filas de la primera y el número de columnas de la segunda. Es decir:

$$A_{rxn}\cdot B_{nxq} = C_{rxq}$$


$$\begin{pmatrix}
5 & 7 & 1 \\
4 & 0 & 2 
\end{pmatrix}\cdot\begin{pmatrix}
0 & 0 \\
2 & 3 \\
2 & 7 
\end{pmatrix}=\begin{pmatrix}
5·0+7·2+1·2 & 5·0+7·3+1·7 \\
4·0+0·2+2·2 & 4·0+0·3+2·7
\end{pmatrix}=\begin{pmatrix}
18 & 28 \\
4 & 14
\end{pmatrix}$$



**Matriz Identidad**

Elemento neutro de la multiplicación, solo $1_s$ en la diagonal:

$$I = \begin{pmatrix}
1&0&\cdots&0&0\\
0&1&\cdots&0&0\\
\vdots&\vdots&\ddots&\vdots&\vdots\\
0&\cdots&\cdots&\cdots&0\\
0&0&\cdots&1&0\\
0&0&\cdots&0&1\\
\end{pmatrix}$$



**Matriz traspuesta  (hermítica)**

La traspuesta $A^{T}$ de una matriz $A$ puede ser obtenida reflejando los elementos a lo largo de su diagonal.

$$A=\begin{pmatrix}
5 & 7 & 9 \\
4 & 0 & 7 \\
1 & 2 & 2
\end{pmatrix}$$

$$A^{T}=\begin{pmatrix}
5 & 4 & 1 \\
7 & 0 & 2 \\
9 & 7 & 2
\end{pmatrix}$$


Se le dice hermítica si los elementos son números complejos, es la traspuesta conjugada (el conjugado de $x+iy$ es $x-iy$).


**Matriz Inversa**

¿Como se dividen las matrices? Se multiplica por la inversa. El cálculo de la matriz inversa es:

$$A= \begin{pmatrix}
       a_{11} & a_{12} \\ 
       a_{21} & a_{22}
    \end{pmatrix}$$
    
    
$$A^{-1}=\begin{pmatrix}
a_{11} & a_{12} \\ 
a_{21} & a_{22}
\end{pmatrix}^{-1}
=\frac{1}{\lvert A\rvert}
\begin{pmatrix}
a_{22} & -a_{12} \\ 
-a_{21} &  a_{11}
\end{pmatrix}$$


**Determinante**

$$A=\begin{pmatrix}
    1 & 3 & 2 & -6 \\ 
    0 & -1 & -4 & 1 \\ 
    0 & -2 & -6 & 3 \\ 
    0 & -2 & -10 & 3
  \end{pmatrix}$$
  

$$$$


$$det(A)=\begin{vmatrix}
    1 & 3 & 2 & -6 \\ 
    0 & -1 & -4 & 1 \\ 
    0 & -2 & -6 & 3 \\ 
    0 & -2 & -10 & 3
  \end{vmatrix}=\begin{vmatrix}
    1 & 0 & 0 \\ 
    -2 & 1 & 0 \\ 
    -2 & 0 & 1
  \end{vmatrix}\cdot
  \begin{vmatrix}
    1 & 4 & 1 \\ 
    2 & 6 & 3 \\ 
    2 & 10 & 3
  \end{vmatrix}=\begin{vmatrix}
    1 & 4 & 1 \\ 
    0 & -2 & 1 \\ 
    0 & 2 & 1
  \end{vmatrix}
  =
  \begin{vmatrix}
    -2 & 1 \\ 
    2 & 1
  \end{vmatrix}
  =-4$$
  
  

**Veamos algo de todo esto en python:**


**Arrays**

In [ ]:
%pip install numpy

In [1]:
import numpy as np

In [2]:
# nº aleatorio

np.random.random(1)

array([0.2660088])

In [3]:
type(np.random.random(1))

numpy.ndarray

In [6]:
type(np.random.random(1)[0])    # el 1 es el nº de elemento, el [0] es el indice

numpy.float64

In [8]:
# vector

vector=np.random.random(5)  # nº alea uniformente distribuidos

vector

array([0.93620742, 0.23600933, 0.8141394 , 0.52918988, 0.35034938])

In [10]:
vector[0:4:2]   # slicing

array([0.93620742, 0.8141394 ])

In [11]:
type(vector)

numpy.ndarray

In [12]:
2 * [1,2,3,4]

[1, 2, 3, 4, 1, 2, 3, 4]

In [13]:
2 * vector

array([1.87241484, 0.47201867, 1.6282788 , 1.05837976, 0.70069877])

In [14]:
# matriz

matriz = np.random.random((10, 4))   # 10 filas, 4 columnas

matriz

array([[0.0361041 , 0.59710372, 0.24219454, 0.33255347],
       [0.02706353, 0.32915959, 0.90029958, 0.59428194],
       [0.30871726, 0.7246228 , 0.83987173, 0.70705214],
       [0.92374425, 0.62016716, 0.72704956, 0.21521253],
       [0.88162452, 0.70789734, 0.75334053, 0.4431825 ],
       [0.30152364, 0.25826505, 0.78301746, 0.95376237],
       [0.12536404, 0.51504111, 0.69091413, 0.18708193],
       [0.89403289, 0.37958908, 0.27329673, 0.03304502],
       [0.63970014, 0.08318278, 0.66963689, 0.42126658],
       [0.69692619, 0.66018722, 0.21225727, 0.72218011]])

In [15]:
type(matriz)

numpy.ndarray

In [18]:
#help(matriz)

In [19]:
matriz.shape   # dimensiones

(10, 4)

In [20]:
matriz.size    # nº de elementos

40

In [21]:
len(matriz)

10

In [22]:
matriz[0]   # la primera fila

array([0.0361041 , 0.59710372, 0.24219454, 0.33255347])

In [23]:
matriz[0][-1]

0.332553474068357

In [25]:
[1,2,3,5].size

AttributeError: 'list' object has no attribute 'size'

**slicing**

los `:` signican todo, es decir, todas las filas. Luego, separado por coma, el 0, primer elemento de cada fila, es decir, la primera columna

In [26]:
matriz

array([[0.0361041 , 0.59710372, 0.24219454, 0.33255347],
       [0.02706353, 0.32915959, 0.90029958, 0.59428194],
       [0.30871726, 0.7246228 , 0.83987173, 0.70705214],
       [0.92374425, 0.62016716, 0.72704956, 0.21521253],
       [0.88162452, 0.70789734, 0.75334053, 0.4431825 ],
       [0.30152364, 0.25826505, 0.78301746, 0.95376237],
       [0.12536404, 0.51504111, 0.69091413, 0.18708193],
       [0.89403289, 0.37958908, 0.27329673, 0.03304502],
       [0.63970014, 0.08318278, 0.66963689, 0.42126658],
       [0.69692619, 0.66018722, 0.21225727, 0.72218011]])

In [27]:
matriz[0, 0]

0.03610410001280806

In [28]:
matriz[:, 0]    # primera columna

array([0.0361041 , 0.02706353, 0.30871726, 0.92374425, 0.88162452,
       0.30152364, 0.12536404, 0.89403289, 0.63970014, 0.69692619])

In [29]:
matriz[0, :]   # primera fila 

array([0.0361041 , 0.59710372, 0.24219454, 0.33255347])

In [30]:
matriz[0]

array([0.0361041 , 0.59710372, 0.24219454, 0.33255347])

In [34]:
matriz[0:2, :]

array([[0.0361041 , 0.59710372, 0.24219454, 0.33255347],
       [0.02706353, 0.32915959, 0.90029958, 0.59428194]])

In [35]:
lst = [1,2,4]

type(lst)

list

In [36]:
array = np.array(lst)

type(array)

numpy.ndarray

In [37]:
# cubo, tensor rango 3

cubo=np.random.random((3, 3, 2))   # capas, filas, columnas

cubo

array([[[0.6999809 , 0.71796484],
        [0.05288659, 0.91001295],
        [0.50160189, 0.46265338]],

       [[0.09535056, 0.70131644],
        [0.99310451, 0.17428253],
        [0.91471014, 0.44934975]],

       [[0.51304965, 0.44488291],
        [0.42896409, 0.94544463],
        [0.76746877, 0.43643942]]])

In [38]:
# tensor rango 4

tensor=np.random.random((2, 3, 4, 5))  # 2 cubos, 3 capas, 4 filas, 5 columnas

tensor

array([[[[1.70529356e-01, 8.20451046e-01, 6.08581848e-01,
          5.66570889e-01, 4.69440676e-01],
         [7.91170425e-01, 5.06295733e-01, 7.52396224e-01,
          7.84642918e-01, 5.11356251e-01],
         [8.98772715e-02, 5.98478223e-01, 1.94946205e-01,
          7.85040114e-01, 6.12028752e-01],
         [6.25895422e-02, 2.01783413e-01, 5.56784375e-01,
          3.80287214e-01, 6.32631657e-01]],

        [[1.30735822e-01, 1.14347539e-02, 8.76467646e-01,
          8.42365220e-01, 5.88748760e-02],
         [5.84483545e-02, 4.84807613e-01, 1.44753372e-01,
          2.76337958e-01, 6.15726807e-01],
         [6.11670973e-01, 6.19539866e-01, 3.36733837e-01,
          3.91113888e-01, 7.61391374e-01],
         [6.68068753e-02, 1.94291983e-01, 6.92995862e-01,
          1.09992186e-01, 2.09781855e-01]],

        [[5.97723584e-01, 6.36620022e-01, 7.79378925e-01,
          6.07986819e-01, 7.66010204e-01],
         [2.87121290e-01, 2.62852073e-01, 4.16803695e-01,
          3.51736718e-01, 4.9

In [39]:
tensor.shape

(2, 3, 4, 5)

In [43]:
tensor[0][0][0][-1]

0.46944067627499486

In [44]:
tensor[0, 0, 0, -1]

0.46944067627499486

**Operaciones matemáticas**

In [45]:
matriz

array([[0.0361041 , 0.59710372, 0.24219454, 0.33255347],
       [0.02706353, 0.32915959, 0.90029958, 0.59428194],
       [0.30871726, 0.7246228 , 0.83987173, 0.70705214],
       [0.92374425, 0.62016716, 0.72704956, 0.21521253],
       [0.88162452, 0.70789734, 0.75334053, 0.4431825 ],
       [0.30152364, 0.25826505, 0.78301746, 0.95376237],
       [0.12536404, 0.51504111, 0.69091413, 0.18708193],
       [0.89403289, 0.37958908, 0.27329673, 0.03304502],
       [0.63970014, 0.08318278, 0.66963689, 0.42126658],
       [0.69692619, 0.66018722, 0.21225727, 0.72218011]])

In [47]:
matriz.sum()

20.41151341201995

In [46]:
sum(matriz)

array([4.83480056, 4.87521584, 6.09187841, 4.6096186 ])

In [49]:
matriz.sum(axis=0)    # suma por columnas

array([4.83480056, 4.87521584, 6.09187841, 4.6096186 ])

In [51]:
matriz.sum(axis=1)    # suma por filas

array([1.20795583, 1.85080463, 2.58026392, 2.4861735 , 2.78604489,
       2.29656853, 1.51840122, 1.57996372, 1.81378639, 2.29155079])

In [52]:
matriz.sum(axis=2)  

AxisError: axis 2 is out of bounds for array of dimension 2

In [53]:
cubo.sum(axis=2)    # suma por capas del cubo

array([[1.41794573, 0.96289954, 0.96425527],
       [0.796667  , 1.16738704, 1.36405989],
       [0.95793256, 1.37440873, 1.20390819]])

In [55]:
matriz[:, 2].sum()

6.0918784100289765

In [57]:
matriz[0].sum()

1.2079558321390196

In [58]:
tensor.shape

(2, 3, 4, 5)

In [61]:
tensor.sum(axis=0).shape     # suma por cubos

(3, 4, 5)

In [62]:
tensor.sum(axis=1).shape     # suma por capas del cubo

(2, 4, 5)

In [63]:
tensor.sum(axis=2).shape     # suma por filas

(2, 3, 5)

In [66]:
tensor.sum(axis=3).shape     # suma por columnas

(2, 3, 4)

In [72]:
tensor.sum(axis=1).sum(axis=1).shape

(2, 5)

In [73]:
matriz.min()

0.02706352602518003

In [74]:
matriz.max()

0.9537623746334511

In [78]:
matriz[0:2, 0:2]  # Aij : matriz[filas, columnas]

array([[0.0361041 , 0.59710372],
       [0.02706353, 0.32915959]])

In [79]:
matriz[0:2, 0:2].max()

0.5971037190794041

In [80]:
matriz.max(axis=0)

array([0.92374425, 0.7246228 , 0.90029958, 0.95376237])

In [81]:
matriz.max(axis=1)

array([0.59710372, 0.90029958, 0.83987173, 0.92374425, 0.88162452,
       0.95376237, 0.69091413, 0.89403289, 0.66963689, 0.72218011])

In [83]:
# calculo del maximo

lst = [54,6, 445646456, 7,8,8,6,5,4,3,5,6,6,6,6,6,7,7777]

def maximo(lst):
    
    el_maximo = 0
    
    for e in lst:
        if e>el_maximo:
            el_maximo=e
    
    
    return el_maximo


maximo(lst)

445646456

In [86]:
%%time

lst = [1,2,3,4]

[e+2 for e in lst]

CPU times: user 42 µs, sys: 1 µs, total: 43 µs
Wall time: 56 µs


[3, 4, 5, 6]

In [87]:
%%time

np.array(lst) + 2   # vectorizacion

CPU times: user 36 µs, sys: 1 µs, total: 37 µs
Wall time: 41 µs


array([3, 4, 5, 6])

In [88]:
matriz.mean()

0.5102878353004987

In [89]:
matriz.mean(axis=0)

array([0.48348006, 0.48752158, 0.60918784, 0.46096186])

In [90]:
matriz.std()

0.2778504174880028

In [91]:
matriz.var()

0.07720085449825746

In [92]:
matriz.var() ** 0.5

0.2778504174880028

In [93]:
matriz.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [94]:
np.median(matriz)

0.5956928283169678

In [97]:
matriz[0:8:2, 0:2]   # matriz[filas_ini:filas_final:filas_step, columnas...]

array([[0.0361041 , 0.59710372],
       [0.30871726, 0.7246228 ],
       [0.88162452, 0.70789734],
       [0.12536404, 0.51504111]])

In [99]:
np.add(matriz[0], matriz[1])    # suma de vectores

array([0.06316763, 0.9262633 , 1.14249412, 0.92683541])

In [100]:
np.subtract(matriz[0], matriz[1])    # resta de vectores

array([ 0.00904057,  0.26794413, -0.65810504, -0.26172846])

In [101]:
matriz[0] + matriz[1]

array([0.06316763, 0.9262633 , 1.14249412, 0.92683541])

In [102]:
np.prod(matriz)      # productorio

3.2337413176432205e-17

In [103]:
1e-17    # notacion cientifica

1e-17

In [104]:
np.multiply(matriz[0], matriz[1])    # producto elemento a elemento (element wise)

array([0.0009771 , 0.19654241, 0.21804764, 0.19763052])

In [108]:
matriz[0][0] * matriz[1][0]

0.0009771042503123335

In [109]:
np.dot(matriz[0], matriz[1])   # producto escalar, producto interno inner

0.6131976814949006

In [110]:
np.dot(matriz, matriz)

ValueError: shapes (10,4) and (10,4) not aligned: 4 (dim 1) != 10 (dim 0)

In [111]:
matriz.shape

(10, 4)

In [112]:
matriz.T.shape   # transposicion, cambia filas por columnas

(4, 10)

In [113]:
matriz.transpose().shape

(4, 10)

In [115]:
np.dot(matriz, matriz.T).shape

(10, 10)

In [116]:
np.dot(matriz.T, matriz).shape

(4, 4)

In [117]:
np.matmul(matriz.T, matriz).shape

(4, 4)

In [118]:
np.cross(matriz[0][:3], matriz[1][:3])

array([ 0.45785157, -0.02594987, -0.00427572])

In [119]:
np.tensordot(matriz, matriz)

array(13.50378117)

In [124]:
matriz

array([[0.0361041 , 0.59710372, 0.24219454, 0.33255347],
       [0.02706353, 0.32915959, 0.90029958, 0.59428194],
       [0.30871726, 0.7246228 , 0.83987173, 0.70705214],
       [0.92374425, 0.62016716, 0.72704956, 0.21521253],
       [0.88162452, 0.70789734, 0.75334053, 0.4431825 ],
       [0.30152364, 0.25826505, 0.78301746, 0.95376237],
       [0.12536404, 0.51504111, 0.69091413, 0.18708193],
       [0.89403289, 0.37958908, 0.27329673, 0.03304502],
       [0.63970014, 0.08318278, 0.66963689, 0.42126658],
       [0.69692619, 0.66018722, 0.21225727, 0.72218011]])

In [120]:
matriz.cumsum()   # suma acumulada

array([ 0.0361041 ,  0.63320782,  0.87540236,  1.20795583,  1.23501936,
        1.56417894,  2.46447852,  3.05876046,  3.36747772,  4.09210052,
        4.93197225,  5.63902438,  6.56276863,  7.18293579,  7.90998535,
        8.12519788,  9.0068224 ,  9.71471974, 10.46806027, 10.91124277,
       11.21276641, 11.47103147, 12.25404893, 13.2078113 , 13.33317534,
       13.84821646, 14.53913058, 14.72621252, 15.62024541, 15.99983448,
       16.27313121, 16.30617623, 16.94587637, 17.02905915, 17.69869604,
       18.11996263, 18.81688882, 19.47707603, 19.68933331, 20.41151341])

In [122]:
matriz.cumprod()    # producto acumulada  

array([3.61041000e-02, 2.15578924e-02, 5.22120381e-03, 1.73632947e-03,
       4.69911977e-05, 1.54676032e-05, 1.39254766e-05, 8.27565923e-06,
       2.55483887e-06, 1.85129450e-06, 1.55484990e-06, 1.09935994e-06,
       1.01552742e-06, 6.29796756e-07, 4.57893456e-07, 9.85444086e-08,
       8.68791671e-08, 6.15015310e-08, 4.63315959e-08, 2.05333526e-08,
       6.19129129e-09, 1.59899418e-09, 1.25204036e-09, 1.19414899e-09,
       1.49703344e-10, 7.71033766e-11, 5.32718122e-11, 9.96619367e-12,
       8.91010493e-12, 3.38217850e-12, 9.24338319e-13, 3.05447814e-14,
       1.95395010e-14, 1.62535001e-15, 1.08839432e-15, 4.58504157e-16,
       3.19543556e-16, 2.10958571e-16, 4.47774910e-17, 3.23374132e-17])

In [123]:
matriz.cumprod(axis=1)

array([[0.0361041 , 0.02155789, 0.0052212 , 0.00173633],
       [0.02706353, 0.00890822, 0.00802007, 0.00476618],
       [0.30871726, 0.22370357, 0.1878823 , 0.13284258],
       [0.92374425, 0.57287584, 0.41650913, 0.08963798],
       [0.88162452, 0.62409965, 0.47015956, 0.20836649],
       [0.30152364, 0.07787302, 0.06097593, 0.05815655],
       [0.12536404, 0.06456764, 0.04461069, 0.00834585],
       [0.89403289, 0.33936512, 0.09274738, 0.00306484],
       [0.63970014, 0.05321204, 0.03563274, 0.01501088],
       [0.69692619, 0.46010176, 0.09765995, 0.07052807]])

In [125]:
np.inf

inf

In [126]:
type(np.inf)

float

In [127]:
np.nan   # not a number, valor nulo

nan

In [128]:
type(np.nan)

float

In [130]:
type(None)

NoneType

In [132]:
np.pi

3.141592653589793

In [133]:
np.exp

<ufunc 'exp'>

In [135]:
np.exp(7)

1096.6331584284585

In [134]:
np.log

<ufunc 'log'>

**Dimensiones**

In [136]:
matriz.shape

(10, 4)

In [137]:
matriz

array([[0.0361041 , 0.59710372, 0.24219454, 0.33255347],
       [0.02706353, 0.32915959, 0.90029958, 0.59428194],
       [0.30871726, 0.7246228 , 0.83987173, 0.70705214],
       [0.92374425, 0.62016716, 0.72704956, 0.21521253],
       [0.88162452, 0.70789734, 0.75334053, 0.4431825 ],
       [0.30152364, 0.25826505, 0.78301746, 0.95376237],
       [0.12536404, 0.51504111, 0.69091413, 0.18708193],
       [0.89403289, 0.37958908, 0.27329673, 0.03304502],
       [0.63970014, 0.08318278, 0.66963689, 0.42126658],
       [0.69692619, 0.66018722, 0.21225727, 0.72218011]])

In [138]:
matriz.reshape((5, 8))

array([[0.0361041 , 0.59710372, 0.24219454, 0.33255347, 0.02706353,
        0.32915959, 0.90029958, 0.59428194],
       [0.30871726, 0.7246228 , 0.83987173, 0.70705214, 0.92374425,
        0.62016716, 0.72704956, 0.21521253],
       [0.88162452, 0.70789734, 0.75334053, 0.4431825 , 0.30152364,
        0.25826505, 0.78301746, 0.95376237],
       [0.12536404, 0.51504111, 0.69091413, 0.18708193, 0.89403289,
        0.37958908, 0.27329673, 0.03304502],
       [0.63970014, 0.08318278, 0.66963689, 0.42126658, 0.69692619,
        0.66018722, 0.21225727, 0.72218011]])

In [139]:
matriz.reshape((8, 5))

array([[0.0361041 , 0.59710372, 0.24219454, 0.33255347, 0.02706353],
       [0.32915959, 0.90029958, 0.59428194, 0.30871726, 0.7246228 ],
       [0.83987173, 0.70705214, 0.92374425, 0.62016716, 0.72704956],
       [0.21521253, 0.88162452, 0.70789734, 0.75334053, 0.4431825 ],
       [0.30152364, 0.25826505, 0.78301746, 0.95376237, 0.12536404],
       [0.51504111, 0.69091413, 0.18708193, 0.89403289, 0.37958908],
       [0.27329673, 0.03304502, 0.63970014, 0.08318278, 0.66963689],
       [0.42126658, 0.69692619, 0.66018722, 0.21225727, 0.72218011]])

In [140]:
matriz.reshape((5, 4, 2))

array([[[0.0361041 , 0.59710372],
        [0.24219454, 0.33255347],
        [0.02706353, 0.32915959],
        [0.90029958, 0.59428194]],

       [[0.30871726, 0.7246228 ],
        [0.83987173, 0.70705214],
        [0.92374425, 0.62016716],
        [0.72704956, 0.21521253]],

       [[0.88162452, 0.70789734],
        [0.75334053, 0.4431825 ],
        [0.30152364, 0.25826505],
        [0.78301746, 0.95376237]],

       [[0.12536404, 0.51504111],
        [0.69091413, 0.18708193],
        [0.89403289, 0.37958908],
        [0.27329673, 0.03304502]],

       [[0.63970014, 0.08318278],
        [0.66963689, 0.42126658],
        [0.69692619, 0.66018722],
        [0.21225727, 0.72218011]]])

In [142]:
matriz.flatten().shape

(40,)

In [143]:
a = (80)

type(a)

int

In [144]:
a = (80,)

type(a)

tuple

In [145]:
matriz

array([[0.0361041 , 0.59710372, 0.24219454, 0.33255347],
       [0.02706353, 0.32915959, 0.90029958, 0.59428194],
       [0.30871726, 0.7246228 , 0.83987173, 0.70705214],
       [0.92374425, 0.62016716, 0.72704956, 0.21521253],
       [0.88162452, 0.70789734, 0.75334053, 0.4431825 ],
       [0.30152364, 0.25826505, 0.78301746, 0.95376237],
       [0.12536404, 0.51504111, 0.69091413, 0.18708193],
       [0.89403289, 0.37958908, 0.27329673, 0.03304502],
       [0.63970014, 0.08318278, 0.66963689, 0.42126658],
       [0.69692619, 0.66018722, 0.21225727, 0.72218011]])

In [148]:
%%time

matriz + np.array([1,2,3,4])

CPU times: user 55 µs, sys: 12 µs, total: 67 µs
Wall time: 71.3 µs


array([[1.0361041 , 2.59710372, 3.24219454, 4.33255347],
       [1.02706353, 2.32915959, 3.90029958, 4.59428194],
       [1.30871726, 2.7246228 , 3.83987173, 4.70705214],
       [1.92374425, 2.62016716, 3.72704956, 4.21521253],
       [1.88162452, 2.70789734, 3.75334053, 4.4431825 ],
       [1.30152364, 2.25826505, 3.78301746, 4.95376237],
       [1.12536404, 2.51504111, 3.69091413, 4.18708193],
       [1.89403289, 2.37958908, 3.27329673, 4.03304502],
       [1.63970014, 2.08318278, 3.66963689, 4.42126658],
       [1.69692619, 2.66018722, 3.21225727, 4.72218011]])

In [149]:
%%time

matriz + [1, 2, 3, 4]

CPU times: user 53 µs, sys: 8 µs, total: 61 µs
Wall time: 58.9 µs


array([[1.0361041 , 2.59710372, 3.24219454, 4.33255347],
       [1.02706353, 2.32915959, 3.90029958, 4.59428194],
       [1.30871726, 2.7246228 , 3.83987173, 4.70705214],
       [1.92374425, 2.62016716, 3.72704956, 4.21521253],
       [1.88162452, 2.70789734, 3.75334053, 4.4431825 ],
       [1.30152364, 2.25826505, 3.78301746, 4.95376237],
       [1.12536404, 2.51504111, 3.69091413, 4.18708193],
       [1.89403289, 2.37958908, 3.27329673, 4.03304502],
       [1.63970014, 2.08318278, 3.66963689, 4.42126658],
       [1.69692619, 2.66018722, 3.21225727, 4.72218011]])

In [153]:
np.stack((matriz, matriz))

array([[[0.0361041 , 0.59710372, 0.24219454, 0.33255347],
        [0.02706353, 0.32915959, 0.90029958, 0.59428194],
        [0.30871726, 0.7246228 , 0.83987173, 0.70705214],
        [0.92374425, 0.62016716, 0.72704956, 0.21521253],
        [0.88162452, 0.70789734, 0.75334053, 0.4431825 ],
        [0.30152364, 0.25826505, 0.78301746, 0.95376237],
        [0.12536404, 0.51504111, 0.69091413, 0.18708193],
        [0.89403289, 0.37958908, 0.27329673, 0.03304502],
        [0.63970014, 0.08318278, 0.66963689, 0.42126658],
        [0.69692619, 0.66018722, 0.21225727, 0.72218011]],

       [[0.0361041 , 0.59710372, 0.24219454, 0.33255347],
        [0.02706353, 0.32915959, 0.90029958, 0.59428194],
        [0.30871726, 0.7246228 , 0.83987173, 0.70705214],
        [0.92374425, 0.62016716, 0.72704956, 0.21521253],
        [0.88162452, 0.70789734, 0.75334053, 0.4431825 ],
        [0.30152364, 0.25826505, 0.78301746, 0.95376237],
        [0.12536404, 0.51504111, 0.69091413, 0.18708193],
        [0.8

In [154]:
vector

array([0.93620742, 0.23600933, 0.8141394 , 0.52918988, 0.35034938])

In [155]:
vector + 10

array([10.93620742, 10.23600933, 10.8141394 , 10.52918988, 10.35034938])

In [156]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [157]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [159]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [160]:
np.where   # condicional

<function numpy.where>

In [161]:
np.where(matriz > 0.5, 1, 0)  # condicion, me das uno else 0

array([[0, 1, 0, 0],
       [0, 0, 1, 1],
       [0, 1, 1, 1],
       [1, 1, 1, 0],
       [1, 1, 1, 0],
       [0, 0, 1, 1],
       [0, 1, 1, 0],
       [1, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 1]])

In [162]:
np.where(matriz > 0.5, 1, np.where(matriz < 0.5, 2, 0))

array([[2, 1, 2, 2],
       [2, 2, 1, 1],
       [2, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [2, 2, 1, 1],
       [2, 1, 1, 2],
       [1, 2, 2, 2],
       [1, 2, 1, 2],
       [1, 1, 2, 1]])